module.exports = {
  plugins: ["eslint-plugin-prettier"],
  extends: ["eslint:all", "eslint-config-prettier"],
  rules: {
    "prettier/prettier": ["error", { printWidth: 120 }],
    "array-bracket-newline": ["error", "consistent"],
    "array-element-newline": "off",
    "arrow-parens": ["error", "always"],
    "capitalized-comments": "off",
    "class-methods-use-this": ["error", { exceptMethods: ["exec"] }],
    "comma-dangle": ["error", "always-multiline"],
    "consistent-return": "off",
    "dot-location": ["error", "property"],
    "function-call-argument-newline": "off",
    "func-style": ["error", "declaration", { allowArrowFunctions: true }],
    "id-length": "off",
    "implicit-arrow-linebreak": "off",
    "lines-between-class-members": "off",
    "max-len": ["error", 120],
    "max-lines": "off",
    "max-lines-per-function": "off",
    "max-statements": "off",
    "multiline-comment-style": ["error", "separate-lines"],
    "multiline-ternary": "off",
    "no-duplicate-imports": "off",
    "no-console": "off",
    "no-magic-numbers": "off",
    "no-process-exit": "off",
    "no-prototype-builtins": "off",
    "no-tabs": "off",
    "no-ternary": "off",
    "no-trailing-spaces": ["error", { skipBlankLines: true }],
    "object-curly-spacing": ["error", "always"],
    "object-property-newline": "off",
    "one-var": ["error", "never"],
    "padded-blocks": ["error", "never"],
    "prefer-destructuring": ["error", { array: true, object: false }],
    "quote-props": ["error", "as-needed"],
    "require-unicode-regexp": "off",
    "sort-keys": "off",
    "sort-imports": "off",
    "space-in-parens": ["error", "never"],
    strict: "off",
  },
};
